import { AdminEmpty, AdminNotice } from "@/components/admin/admin-page";
import { dateLabel } from "@/lib/content";
import { requireAdmin } from "@/lib/admin-auth";
import { createClient } from "@/lib/supabase/server";
import { createActionItem, createMeeting } from "../operations/actions";

export default async function GovernancePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin(); const supabase = await createClient();
  const [meetings, actions] = await Promise.all([supabase.from("session_meetings").select("id,title,scheduled_at,venue,status").order("scheduled_at", { ascending: false }).limit(30), supabase.from("action_items").select("id,title,due_on,status,meeting_id").neq("status", "complete").order("due_on").limit(30)]);
  return <main className="admin-main"><header className="admin-page-header"><div><p>Session administration</p><h1>Governance</h1><span>Prepare meetings, retain decisions and track responsibility.</span></div></header><AdminNotice params={await searchParams} /><div className="admin-content-layout"><div><section className="admin-section"><div className="admin-section-title"><h2>Session meetings</h2></div>{meetings.data?.length ? <div className="admin-table">{meetings.data.map(meeting => <article key={meeting.id}><div><strong>{meeting.title}</strong><span>{dateLabel(meeting.scheduled_at, true)} GMT · {meeting.venue || "Venue pending"}</span></div><span className={`admin-status admin-status-${meeting.status === "completed" ? "published" : "draft"}`}>{meeting.status}</span></article>)}</div> : <AdminEmpty title="No Session meetings">Schedule the first meeting and prepare its agenda.</AdminEmpty>}</section><section className="admin-section"><div className="admin-section-title"><h2>Open actions</h2></div>{actions.data?.length ? <div className="admin-table">{actions.data.map(item => <article key={item.id}><div><strong>{item.title}</strong><span>{item.due_on ? `Due ${dateLabel(item.due_on)}` : "No due date"}</span></div><span className="admin-status admin-status-draft">{item.status}</span></article>)}</div> : <AdminEmpty title="No open actions">Actions agreed by Session will appear here.</AdminEmpty>}</section></div><aside className="admin-editor-column"><section className="admin-section admin-editor"><h2>Schedule Session</h2><form action={createMeeting}><label>Meeting title<input name="title" required maxLength={200} /></label><label>Date and time<input name="scheduled_at" type="datetime-local" required /></label><label>Venue<input name="venue" maxLength={300} /></label><label>Agenda<textarea name="agenda" rows={5} /></label><label>Status<select name="status" defaultValue="scheduled"><option value="draft">Draft</option><option value="scheduled">Scheduled</option></select></label><button className="admin-button admin-button-primary" type="submit">Save meeting</button></form></section><section className="admin-section admin-editor"><h2>Add action item</h2><form action={createActionItem}><label>Meeting<select name="meeting_id" defaultValue=""><option value="">General action</option>{meetings.data?.map(meeting => <option key={meeting.id} value={meeting.id}>{meeting.title}</option>)}</select></label><label>Action<input name="title" required maxLength={300} /></label><label>Due on<input name="due_on" type="date" /></label><button className="admin-button admin-button-secondary" type="submit">Add action</button></form></section></aside></div></main>;
}

