import type { Metadata } from "next";
import Image from "next/image";
import { Container } from "@/components/ui/container";
import { ButtonLink, PageIntro, Prose, ServiceList } from "@/components/ui/public-page";
import { ContactForm } from "@/components/contact-form";
import { getCopy, getSettings } from "@/lib/content";
import { contactEnabled } from "@/lib/contact-config";
export const metadata: Metadata = { title: "Plan Your Visit", description: "Plan your first visit to Peace Be Congregation in Community 25, Tema." };
export default async function VisitPage() {
  const [copy, settings] = await Promise.all([getCopy("visit.what_to_expect"), getSettings()]);
  return <><PageIntro title="You are welcome here." label="Plan your visit" intro="Your first visit doesn’t have to feel unfamiliar. Let’s help you feel at home." /><Container><section className="section split-section"><div><h2>Join us for worship</h2><ServiceList /></div><div className="location-panel"><figure className="visit-building"><Image src="/images/peace-be-building-side.webp" alt="Architectural rendering of the new Peace Be Congregation church building, now under construction, seen from the side, showing the timber-clad front with the cross and church name and the blue three-storey wing behind it" width={1080} height={701} sizes="(max-width: 760px) 100vw, 560px" /><figcaption>Our new church building, currently under construction (architectural rendering)</figcaption></figure><p className="section-label">Find us</p><h2>Community 25, Tema</h2><p>{settings?.address || "Peace Be Congregation, Community 25, Tema, Ghana"}</p><p className="muted">Our new building is still under construction. Please contact the church for the exact location and directions before travelling.</p>{settings?.phone && <a className="text-link" href={"tel:" + settings.phone.replace(/[^+\d]/g, "")}>Call {settings.phone}</a>}<ButtonLink href="/contact" secondary>Ask for directions</ButtonLink></div></section><section className="section section-rule split-section"><h2>Your first Sunday</h2><div><Prose>{copy || "Come ready to join in worship and hear God’s Word. You don’t need to be a member to visit. If you’re unsure where to go when you arrive, let someone know it’s your first time and ask for a welcome team member."}</Prose><div className="faq"><details><summary>Do I need to register before visiting?</summary><p>You can visit without registering through this website. If you would like help planning your visit, send us a message below.</p></details><details><summary>Can I come with my children?</summary><p>Families are welcome. Ask the church about children’s arrangements and the programme for the service you plan to attend.</p></details><details><summary>What should I wear?</summary><p>Wear something you feel comfortable in for a church service. You are welcome as you are.</p></details><details><summary>What if I need accessibility support?</summary><p>Tell us what would help before you visit so the church can confirm the arrangements available.</p></details></div></div></section><section className="section section-rule split-section"><div><h2>Let us know you’re coming.</h2><p className="muted">Have a question or need a little help planning? Leave a message for the church office.</p></div><ContactForm type="visitor" enabled={contactEnabled()} /></section></Container></>;
}
