import { AdminEmpty, AdminNotice } from "@/components/admin/admin-page";
import { requireAdmin } from "@/lib/admin-auth";
import { createClient } from "@/lib/supabase/server";
import { createPerson } from "../operations/actions";

export default async function MembersPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin();
  const supabase = await createClient();
  const [{ data: people }, { count: households }] = await Promise.all([
    supabase.from("people").select("id,first_name,last_name,preferred_name,phone,email,status,member_number,created_at").order("last_name").limit(100),
    supabase.from("households").select("id", { count: "exact", head: true }),
  ]);
  const params = await searchParams;
  return <main className="admin-main"><header className="admin-page-header"><div><p>Membership and households</p><h1>People</h1><span>Maintain the congregation register and member contact records.</span></div></header><AdminNotice params={params} /><section className="admin-metrics" aria-label="Membership summary"><div><strong>{people?.length ?? 0}</strong><span>People loaded</span></div><div><strong>{households ?? 0}</strong><span>Households</span></div><div><strong>{people?.filter(person => person.status === "member" || person.status === "communicant").length ?? 0}</strong><span>Active members</span></div><div><strong>{people?.filter(person => person.status === "visitor").length ?? 0}</strong><span>Visitors</span></div></section><div className="admin-content-layout"><section className="admin-section"><div className="admin-section-title"><h2>Congregation register</h2><span>Up to 100 records</span></div>{people?.length ? <div className="admin-table">{people.map(person => <article key={person.id}><div><strong>{person.preferred_name || person.first_name} {person.last_name}</strong><span>{person.member_number || "No member number"} · {person.phone || person.email || "No contact recorded"}</span></div><span className="admin-status admin-status-published">{person.status}</span></article>)}</div> : <AdminEmpty title="No member records yet">Add the first verified person using the form.</AdminEmpty>}</section><aside className="admin-editor-column"><section className="admin-section admin-editor"><h2>Add a person</h2><form action={createPerson}><div className="admin-form-grid"><label>First name<input name="first_name" required maxLength={100} /></label><label>Last name<input name="last_name" required maxLength={100} /></label></div><label>Preferred name<input name="preferred_name" maxLength={100} /></label><div className="admin-form-grid"><label>Phone<input name="phone" type="tel" maxLength={40} /></label><label>Email<input name="email" type="email" maxLength={320} /></label></div><div className="admin-form-grid"><label>Status<select name="status" defaultValue="member"><option value="visitor">Visitor</option><option value="member">Member</option><option value="communicant">Communicant</option><option value="inactive">Inactive</option><option value="transferred">Transferred</option></select></label><label>Joined on<input name="joined_on" type="date" /></label></div><div className="admin-check-row"><label><input name="directory_visible" type="checkbox" /> Member permits directory visibility</label></div><button className="admin-button admin-button-primary" type="submit">Save person</button></form></section></aside></div></main>;
}

