import Image from "next/image";
import Link from "next/link";
import { Container } from "@/components/ui/container";
import { Arrow, ButtonLink, ContentImage, EmptyState, EventList, SectionHeading, SermonList, ServiceList } from "@/components/ui/public-page";
import { dateLabel, getAlmanacEntry, getAnnouncements, getCampaigns, getCopy, getEvents, getSermons, getStories, ghanaDate } from "@/lib/content";

export default async function HomePage() {
  const [events, sermons, announcements, welcome, almanac, campaigns, stories] = await Promise.all([getEvents(), getSermons(), getAnnouncements(), getCopy("home.welcome"), getAlmanacEntry(ghanaDate()), getCampaigns(), getStories()]);
  const today = almanac.data[0];
  const harvest = campaigns.data.find(campaign => campaign.status === "active");
  return <>
    <section className="home-hero"><Container className="hero-grid"><div className="hero-copy"><p className="hero-location"><span /> Community 25, Tema</p><h1>A place to belong.<br />A faith to live.</h1><p>{welcome || "Welcome to Peace Be Congregation. A family in Christ, growing in faith and sharing God’s love with our community."}</p><div className="button-group"><ButtonLink href="/visit">Come worship with us</ButtonLink><Link href="/about" className="hero-about">Meet our church <Arrow /></Link></div><div className="hero-signature"><span className="small-cross" aria-hidden="true">✝</span><span>Presbyterian Church of Ghana<br /><strong>Peace be with you.</strong></span></div></div><figure className="hero-image"><Image src="/images/peace-be-building.webp" alt="Architectural rendering of the Peace Be Congregation church building, with a cross and the church name on its timber-clad front wall" fill preload sizes="(max-width: 760px) 100vw, 48vw" /><figcaption>Our church home in Community 25, Tema</figcaption></figure></Container></section>
    <section className="welcome-strip"><Container className="welcome-strip-inner"><p>New here? <strong>There’s a place for you.</strong></p><Link href="/visit" className="text-link">Everything you need for your first visit <Arrow /></Link></Container></section>
    <section className="home-daily"><Container className="home-daily-grid"><div><p className="section-label">Today at Peace Be</p><h2>{today?.theme || today?.day_label || "Begin the day with Scripture and prayer."}</h2><p>{today?.memory_verse_reference || "The approved daily Almanac guide will appear here."}</p><Link href="/today" className="text-link">Open today’s guide <Arrow /></Link></div><div><p className="section-label">Harvest</p><h2>{harvest?.name || "Giving together for God’s work."}</h2><p>{harvest ? `${Math.round(Number(harvest.confirmed_amount) / Number(harvest.target_amount) * 100)}% of the confirmed target reached.` : "Follow the current campaign and see confirmed progress."}</p><Link href="/harvest" className="text-link">View Harvest <Arrow /></Link></div></Container></section>
    <section className="theme-banner" aria-labelledby="theme-2026"><Container><figure><Image src="/images/pcg-theme-2026.jpg" alt="Presbyterian Church of Ghana 2026 theme banner" width={2560} height={1176} sizes="(max-width: 1248px) 100vw, 1200px" /><figcaption><p className="section-label" id="theme-2026">PCG theme for 2026</p><p className="theme-text">Celebrating our heritage: building on the foundation already laid.</p><p className="theme-ref">1 Corinthians 3:11</p></figcaption></figure></Container></section>
    <Container><section className="section home-welcome"><div><p className="section-label">Welcome to Peace Be</p><h2>Church is more<br />than a Sunday.</h2><p className="muted">It’s a life shared. In worship, in friendship, and in the everyday ways we care for one another.</p><ButtonLink href="/about" secondary>Get to know us</ButtonLink></div><div className="service-panel"><h2>Let’s worship together</h2><ServiceList /><Link href="/visit" className="text-link">Plan your visit <Arrow /></Link></div></section>
    <section className="section section-rule"><SectionHeading title="Life in our church" href="/events" link="Explore events" />{events.data.length ? <EventList events={events.data.slice(0, 3)} /> : <EmptyState available={events.available} title="Our next gathering starts here">Upcoming events will appear here once announced. Explore our groups to find ways to take part.</EmptyState>}</section>
    <section className="belong-section"><div><p className="section-label">Faith grows in community</p><h2>Find your people.<br />Grow together.</h2><p>Discover fellowship, friendship and opportunities to serve through the groups and ministries of Peace Be.</p><ButtonLink href="/church-family">Explore our church family</ButtonLink></div><div className="belong-words" aria-hidden="true"><span>Worship.</span><span>Fellowship.</span><span>Service.</span></div></section>
    <section className="section home-updates"><div><SectionHeading title="From the pulpit" href="/sermons" link="All sermons" />{sermons.data.length ? <SermonList sermons={sermons.data.slice(0, 2)} /> : <EmptyState available={sermons.available} title="Make room for the Word">Sermon recordings will be available here after they are published.</EmptyState>}</div><div><SectionHeading title="Church notices" href="/announcements" link="All notices" />{announcements.data.length ? announcements.data.slice(0, 2).map(a => <article className="notice-preview" key={a.id}>{a.is_pinned && <span className="badge">Church notice</span>}<h3><Link href={`/announcements#notice-${a.id}`}>{a.title}</Link></h3><p>{a.body.slice(0, 180)}{a.body.length > 180 ? "…" : ""}</p></article>) : <EmptyState available={announcements.available} title="You’re all caught up">There are no current announcements. Check back for updates from the church.</EmptyState>}</div></section></Container>
    <Container><section className="section section-rule"><SectionHeading title="Stories from Peace Be" href="/stories" link="All stories" />{stories.data.length ? <article className="home-story"><ContentImage fileKey={stories.data[0].cover_image_key} alt={stories.data[0].title} /><div><p className="meta">{dateLabel(stories.data[0].published_at)}</p><h2>{stories.data[0].title}</h2><p>{stories.data[0].excerpt || stories.data[0].body.slice(0, 220)}</p><Link className="text-link" href={`/stories/${stories.data[0].slug}`}>Read the story <Arrow /></Link></div></article> : <EmptyState available={stories.available} title="Our congregation story is still being written">Church life, testimonies and milestones will appear here after office review.</EmptyState>}</section></Container>
    <section className="visit-banner"><Container><div><h2>Your next Sunday<br />could feel like home.</h2><p>Come as you are. We look forward to welcoming you.</p></div><ButtonLink href="/visit">Plan your first visit</ButtonLink></Container></section>
  </>;
}
