import type { Metadata } from "next";
import { Container } from "@/components/ui/container";
import { ButtonLink, PageIntro, Prose } from "@/components/ui/public-page";
import { getCopy, getSettings } from "@/lib/content";
export const metadata: Metadata = { title: "Giving", description: "Find giving information for Peace Be Congregation." };
export default async function GivePage() {
  const [copy, settings] = await Promise.all([getCopy("give.intro"), getSettings()]);
  const bank = settings?.bank_details;
  return <><PageIntro title="A generous heart." label="Giving" intro="Thank you for supporting the life and ministry of Peace Be Congregation." /><Container><section className="section split-section"><div><h2>Giving with purpose</h2><Prose>{copy || "Giving is one way we express our gratitude to God and share in the work of the church. Thank you for considering a gift to Peace Be Congregation."}</Prose></div><div className="giving-options"><section><h3>Give in person</h3><p>You can give when you worship with us. Please speak with the church about tithes, offerings or a gift for a specific purpose.</p></section><section><h3>Mobile money</h3>{settings?.momo_number && settings.momo_name ? <dl><dt>Recipient</dt><dd>{settings.momo_name}</dd><dt>Number</dt><dd className="account-number">{settings.momo_number}</dd></dl> : <p className="muted">Contact the church office for confirmed mobile money details.</p>}</section><section><h3>Bank transfer</h3>{bank?.bank && bank.account_name && bank.account_number ? <dl><dt>Bank</dt><dd>{bank.bank}{bank.branch ? " · " + bank.branch : ""}</dd><dt>Account name</dt><dd>{bank.account_name}</dd><dt>Account number</dt><dd className="account-number">{bank.account_number}</dd></dl> : <p className="muted">Contact the church office for confirmed bank account details.</p>}</section><p className="giving-note">Check the recipient name before completing a transfer. The church will never ask you to share your PIN or one-time password.</p></div></section><section className="simple-callout"><div><h2>A question about your gift?</h2><p>Speak to the church office for help or acknowledgement.</p></div><ButtonLink href="/contact">Contact the church</ButtonLink></section></Container></>;
}
