import { AdminEmpty, AdminNotice } from "@/components/admin/admin-page";
import { dateLabel } from "@/lib/content";
import { requireAdmin } from "@/lib/admin-auth";
import { createClient } from "@/lib/supabase/server";
import { createFund, recordGiving } from "../operations/actions";

const money = new Intl.NumberFormat("en-GH", { style: "currency", currency: "GHS" });
export default async function FinancePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin(); const supabase = await createClient();
  const [funds, transactions] = await Promise.all([supabase.from("funds").select("id,name,is_active").order("name"), supabase.from("giving_transactions").select("id,amount,status,received_at,payment_method,funds(name)").order("received_at", { ascending: false }).limit(30)]);
  const confirmed = transactions.data?.filter(item => item.status === "confirmed").reduce((sum, item) => sum + Number(item.amount), 0) ?? 0;
  return <main className="admin-main"><header className="admin-page-header"><div><p>Stewardship and reconciliation</p><h1>Finance</h1><span>Record giving, maintain funds and preserve an auditable ledger.</span></div></header><AdminNotice params={await searchParams} /><section className="admin-metrics"><div><strong>{money.format(confirmed)}</strong><span>Confirmed in view</span></div><div><strong>{transactions.data?.filter(item => item.status === "pending").length ?? 0}</strong><span>Pending</span></div><div><strong>{funds.data?.length ?? 0}</strong><span>Funds</span></div><div><strong>{transactions.data?.length ?? 0}</strong><span>Recent entries</span></div></section><div className="admin-content-layout"><section className="admin-section"><div className="admin-section-title"><h2>Recent transactions</h2></div>{transactions.data?.length ? <div className="admin-table">{transactions.data.map(item => <article key={item.id}><div><strong>{money.format(Number(item.amount))}</strong><span>{dateLabel(item.received_at)} · {item.payment_method || "Method not recorded"}</span></div><span className={`admin-status admin-status-${item.status === "confirmed" ? "published" : "draft"}`}>{item.status}</span></article>)}</div> : <AdminEmpty title="No transactions recorded">Create a fund, then record confirmed or pending giving.</AdminEmpty>}</section><aside className="admin-editor-column"><section className="admin-section admin-editor"><h2>Record giving</h2><form action={recordGiving}><label>Fund<select name="fund_id" required defaultValue=""><option value="" disabled>Select a fund</option>{funds.data?.map(fund => <option key={fund.id} value={fund.id}>{fund.name}</option>)}</select></label><label>Amount (GHS)<input name="amount" type="number" min="0.01" step="0.01" required /></label><div className="admin-form-grid"><label>Method<input name="payment_method" maxLength={80} placeholder="Cash, MoMo, bank" /></label><label>Reference<input name="payment_reference" maxLength={200} /></label></div><label>Status<select name="status" defaultValue="confirmed"><option value="confirmed">Confirmed</option><option value="pending">Pending reconciliation</option></select></label><button className="admin-button admin-button-primary" type="submit" disabled={!funds.data?.length}>Record transaction</button></form></section><section className="admin-section admin-editor"><h2>Create fund</h2><form action={createFund}><label>Name<input name="name" required maxLength={160} /></label><label>Description<textarea name="description" rows={3} maxLength={1000} /></label><button className="admin-button admin-button-secondary" type="submit">Create fund</button></form></section></aside></div></main>;
}

