import { AdminEmpty, AdminNotice } from "@/components/admin/admin-page";
import { requireAdmin } from "@/lib/admin-auth";
import { createClient } from "@/lib/supabase/server";
import { createMinistry } from "../operations/actions";

export default async function MinistryPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin(); const supabase = await createClient();
  const { data: groups } = await supabase.from("groups").select("id,name,short_name,group_kind,is_public,meeting_day,meeting_time").order("sort_order");
  return <main className="admin-main"><header className="admin-page-header"><div><p>Groups and participation</p><h1>Ministry</h1><span>Organise generational groups, ministries, committees and shepherding structures.</span></div></header><AdminNotice params={await searchParams} /><div className="admin-content-layout"><section className="admin-section"><div className="admin-section-title"><h2>Groups and ministries</h2><span>{groups?.length ?? 0} total</span></div>{groups?.length ? <div className="admin-table">{groups.map(group => <article key={group.id}><div><strong>{group.name}</strong><span>{group.short_name || "No short name"}</span></div><span className={`admin-status ${group.is_public ? "admin-status-published" : "admin-status-draft"}`}>{group.group_kind}</span></article>)}</div> : <AdminEmpty title="No ministries yet">Create the approved congregation structure using the form.</AdminEmpty>}</section><aside className="admin-editor-column"><section className="admin-section admin-editor"><h2>Add a ministry or group</h2><form action={createMinistry}><label>Name<input name="name" required maxLength={160} /></label><label>Short name<input name="short_name" maxLength={30} /></label><label>Type<select name="group_kind" defaultValue="ministry"><option value="generational">Generational group</option><option value="intergenerational">Intergenerational group</option><option value="ministry">Ministry</option><option value="committee">Committee</option><option value="shepherding">Shepherding group</option></select></label><label>Description<textarea name="description" rows={5} maxLength={5000} /></label><div className="admin-check-row"><label><input name="is_public" type="checkbox" defaultChecked /> Show on public website</label></div><button className="admin-button admin-button-primary" type="submit">Save ministry</button></form></section></aside></div></main>;
}

